osx_image_folder: '/Users/vik748/Google Drive/data/time_lapse_5_cervino_800x600'
linux_image_folder: '/home/vik748/data/time_lapse_5_cervino_800x600'
bag_name: '/home/vik748/data/time_lapse_5_cervino_800x600_clahe.bag'
image_ext: 'png'
frequency: 1.0
display_images: False
image_topic: camera/image_raw
image_w_feat_topic: image_with_feat

use_masks: False
osx_masks_folder: ''
linux_masks_folder: ''

use_clahe: True
CLAHE_settings:
 clipLimit: 10.0
 tileGridSize: !!python/tuple [8,6]

ZERNIKE_settings:
 Nfeats: 600
 seci: 2 
 secj: 3
 levels: 6
 ratio: 0.75
 sigi: 2.75
 sigd: 1.0
 nmax: 8
 like_matlab: False
 lmax_nd: 3
